name: tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  tests:
    name: Py${{ matrix.python-version }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        python-version: [3.5, 3.6, 3.7, 3.8, 3.9]
        pyver: [cp36-cp36m, cp37-cp37m, cp38-cp38, cp39-cp39]
        exclude:
          - os: windows-latest
            python-version: 2.7

    steps:
      - uses: actions/checkout@v2.3.3
        with:
          submodules: recursive

      - uses: actions/setup-python@v2
        with:
          python-version: "${{ matrix.python-version }}"
          
      - name: Set up QEMU
        if: startsWith(matrix.os, 'ubuntu-latest')
        id: qemu
        uses: docker/setup-qemu-action@v1

      ## Start Windows stuff
      - uses: ilammy/msvc-dev-cmd@v1.5.0
        if: startsWith(matrix.os, 'windows')

      - name: Set Windows Compiler
        if: startsWith(matrix.os, 'windows')
        run: |
          echo "CC=cl.exe" >> $GITHUB_ENV
          echo "CXX=cl.exe" >> $GITHUB_ENV
      ## End Windows stuff

      - name: Install from source
        run: |
          pip install --upgrade pip setuptools wheel
          pip install .[all]

      - name: Tests
        run: pytest --cov=h3 --full-trace
        
      - name: Test with pytest
        if: startsWith(matrix.os, 'ubuntu-latest')
        run: |
          docker run --rm -v ${{ github.workspace }}:/ws:rw --workdir=/ws \
            quay.io/pypa/manylinux2014_aarch64 \
            bash -exc '/opt/python/${{ matrix.pyver }}/bin/python -m pip install virtualenv && \
            /opt/python/${{ matrix.pyver }}/bin/python -m venv .env && \
            source .env/bin/activate && \
            pip install pytest setuptools wheel && \
            pip install .[all] && \
            pytest --cov=h3 --full-trace && \
            deactivate'
